In [1]:
# importing libraries 
import pandas as pd

In [2]:
# reading the dataset 
df=pd.read_csv("C:/Users/Shalabh Tripathi/Desktop/imp/ML model training/15_diabetes prediction/data/cleaned_csv")

In [3]:
df.head()

,Unnamed: 0,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,Female,80,0,1,never,25.19,6.6,140,0
1,1,Female,54,0,0,No Info,27.32,6.6,80,0
2,2,Male,28,0,0,never,27.32,5.7,158,0
3,3,Female,36,0,0,current,23.45,5.0,155,0
4,4,Male,76,1,1,current,20.14,4.8,155,0

In [4]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [5]:
# extracting labels and features
x=df.drop("diabetes",axis=1)
y=df["diabetes"]

In [6]:
# train test split 
from  sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [7]:
x_train.shape,y_train.shape

((72109, 8), (72109,))

In [8]:
x_test.shape,y_test.shape

((24037, 8), (24037,))

In [9]:
x_train.head(1)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
5096,Female,14,0,0,No Info,21.8,3.5,126

In [10]:
# creating pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [11]:
preprocessor=ColumnTransformer(
    transformers=[
        ("OHE",OneHotEncoder(),[0,4]),
        ("scaler",StandardScaler(),[1,5,6,7])

    ],
    remainder="passthrough"
)

In [12]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('OHE', OneHotEncoder(), [0, 4]),
                                ('scaler', StandardScaler(), [1, 5, 6, 7])])

In [13]:
x_train_preprocessed=preprocessor.fit_transform(x_train)
x_test_preprocessed=preprocessor.transform(x_test)

## Training model:

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

models = {
    "lr": LogisticRegression(),                 # Logistic Regression
    "dt": DecisionTreeClassifier(),             # Decision Tree
    "rf": RandomForestClassifier(),             # Random Forest
    "knn": KNeighborsClassifier(),              # K-Nearest Neighbors
    "svm": SVC(),                              # Support Vector Machine
    "gb": GradientBoostingClassifier()          # Gradient Boosting
}

for name,model in models.items():
    model.fit(x_train_preprocessed,y_train)
    y_preds=model.predict(x_test_preprocessed)

    print(f" {name} Accuracy score ;{accuracy_score(y_preds,y_test)}")

 lr Accuracy score ;0.9574406123892333
 dt Accuracy score ;0.9490785039730416
 rf Accuracy score ;0.9681324624537172
 knn Accuracy score ;0.9586470857428132
 svm Accuracy score ;0.9630985563922286
 gb Accuracy score ;0.9705038066314432

Here the gradient boosting classifier works well.

## Selecting model and traning

In [18]:
model=GradientBoostingClassifier()

In [19]:
model.fit(x_train_preprocessed,y_train)

GradientBoostingClassifier()

In [20]:
# pickle the file 
import pickle 
pickle.dump(model,open("model.pkl","wb"))
pickle.dump(preprocessor,open("preprocessor.pkl","wb"))